-- MySQL Script generated by MySQL Workbench
-- Sat Mar  6 15:03:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ya_Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ya_Buyer` (
  `ya_BuyerID` INT NOT NULL,
  `ya_LastName` CHAR(25) NOT NULL,
  `ya_FirstName` CHAR(25) NOT NULL,
  `ya_Phone` CHAR(12) NOT NULL,
  PRIMARY KEY (`ya_BuyerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ya_Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ya_Vendor` (
  `ya_VendorID` INT NOT NULL,
  `ya_VendorPhone` CHAR(12) NOT NULL,
  `ya_ItemVendor` CHAR(35) NOT NULL,
  `ya_Address` CHAR(25) NULL,
  `ya_City` CHAR(25) NULL,
  `ya_State` CHAR(25) NULL,
  `ya_ZIP` CHAR(5) NULL,
  PRIMARY KEY (`ya_VendorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ya_Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ya_Invoice` (
  `ya_InvoiceID` INT NOT NULL,
  `ya_InvoiceItem` CHAR(25) NOT NULL,
  `ya_InvoiceDate` DATE NULL,
  `ya_Price` DECIMAL(6,2) NOT NULL,
  `ya_Buyer_ya_BuyerID` INT NOT NULL,
  `ya_Vendor_ya_VendorID` INT NOT NULL,
  PRIMARY KEY (`ya_InvoiceID`),
  INDEX `fk_ya_Invoice_ya_Buyer_idx` (`ya_Buyer_ya_BuyerID` ASC) VISIBLE,
  INDEX `fk_ya_Invoice_ya_Vendor1_idx` (`ya_Vendor_ya_VendorID` ASC) VISIBLE,
  CONSTRAINT `fk_ya_Invoice_ya_Buyer`
    FOREIGN KEY (`ya_Buyer_ya_BuyerID`)
    REFERENCES `mydb`.`ya_Buyer` (`ya_BuyerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ya_Invoice_ya_Vendor1`
    FOREIGN KEY (`ya_Vendor_ya_VendorID`)
    REFERENCES `mydb`.`ya_Vendor` (`ya_VendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
